### ISSUE TITLE
[Proposal] FlagD KubeAPI iNotify/ISync service

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/research#15]
FlagD is often used in the context of Kubernetes.

It is typically deployed by [OFO](https://github.com/open-feature/open-feature-operator) as a companion sidecar and uses a volume injected via configmap as the source of its flags to evaluate.

I propose there may be a more optimal way to enable faster refreshing on flag changes by subscribing to a notifier against the Kubernetes API. This is inspired by [this](https://github.com/open-feature/research/issues/1#issuecomment-1144915280) discussion with @therealmitchconnors and also the regression in being able to trigger configmap volume reloads through updating annotations within a deployment.

This is not a silverbullet and I think for academic purposes alone it is worth exploring if we would want to move in this direction. 
**The only real benefit here is speed of flag updates.**

### Design

FlagD would start with the typical arguments of `flagd start --sync-service kubernetes-api` or something similar. 
This would use the token mounted from `/var/run/secrets/kubernetes.io/serviceaccount` to request to watch events for the FeatureFlagConfiguration. The FeatureFlagConfiguration could be determined by the pod getting its own annotations on start through the API and performing a look-up.

![image](https://user-images.githubusercontent.com/1235925/177578898-96fa5511-9010-4d8b-90ac-60d3b7edced6.png)

### Benefits

- Near real-time updates to flags within FlagD and presented to the service layer

### Caveats

- Additional stress on the API Server; it becomes a watcher per open-feature enabled pod; I am [wary of this design pattern](https://github.com/open-feature/research/issues/1#issue-1243922917)
- This would intractably tightly couple FlagD to the Kubernetes golang bindings and limit multi-arch compatibility

**Comment by beeme1mr** [comment]
Hey @AlexsJones, thanks for putting this together! I'm very interested in this because near real-time updates are important for a number of use cases including using feature flagging as a circuit breaker or for problem remediation.

Do you know how much stress this will put on the API server? I would expect a watcher to be computationally inexpensive but that just an assumption. If necessary, it may be possible to use a proxy to reduce the load on the API server itself. It would also be possible to run FlagD as a daemon or service if we need to reduce the number of active connections to the API server.

Do you know what architectures would no longer be supported if we used the Kubernetes Golang bindings?

**Comment by AlexsJones** [comment]
https://github.com/open-feature/research/blob/main/004-OFEP-inotify-interface.md
